### ISSUE TITLE
Cannot set property 'parseUrl' of undefined

### ISSUE THREAD

**Issue by schuylr** [MindscapeHQ/raygun4js#126]
Message: Cannot set property 'parseUrl' of undefined
     at raygunJsUrlFactory (eval at <anonymous> line 2, column 7052 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:2:22756), <anonymous>:2)
     at eval (eval at <anonymous> line 2, column 8804 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:2:22756), <anonymous>:2)
     at at line 2, column 22756 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:2)
     at Function.re.extend.globalEval line 2, column 22767 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:2)
     at re.ajaxSetup.converters.text script line 5, column 1829 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:5)
     at B line 2, column 19795 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:2)
     at n line 4, column 27743 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:4)
     at e line 5, column 1471 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:5)
     at Object.send line 5, column 1575 (https://www.jewlr.com/assets/application-8a7fd0b59333a169ad6b7980dc9c0f26.js:5)

Suspect to be caused [here](https://github.com/MindscapeHQ/raygun4js/blob/58aa69abd127ed0c00c4ac56aa23bef06a7bb9cc/dist/raygun.js#L1969)

**Comment by fundead** [comment]
Hello,

This error can be seen in certain circumstances where raygun4js is included multiple times with duplicate script tags for instance. I notice there is an `eval` in the stacktrace, can you provide details on how raygun4js is being included/bundled together with other scripts?

**Comment by schuylr** [comment]
@fundead It's bundled in the Rails assets pipeline (in the resulting `application.js`), at the top of the script. The minified Raygun4js and `Raygun.init` are in the same file.

**Comment by fundead** [comment]
Thanks for that, this process is known to work in other frameworks so there will be an issue to track down here. What version of Rails are you running?

**Comment by schuylr** [comment]
My `Gemfile.lock` shows Rails 4.2.3 :)

For now, I'll move the file up into a file outside of the Asset Pipeline and see if it remedies the problem. Raygun reports that the error is only happening on Chrome.

**Comment by jgentes** [comment]
I'm seeing this with AngularJS using the Javascript agent: `Uncaught TypeError: Cannot set property 'parseUrl' of undefined`

```
raygunJsUrlFactory @ raygun.js:2575
(anonymous function) @ raygun.js:2653
```

**Comment by jgentes** [comment]
@dwnz any thoughts what might be causing it? Happens every time a page loads.

**Comment by fundead** [comment]
Can you provide details on how you're referencing the script - e.g with the CDN and snippet/a package manager/manually referenced and whether or not it is bundled or uses a clientside package manager?

Also if you could inspect your dev tools and confirm that raygun.min.js is only loaded once that would be helpful to rule out.

**Comment by jgentes** [comment]
Yep, I was loading it twice. Sorry about that - used the script then later added it via bower. Glad it was an easy fix!

**Comment by fundead** [comment]
Great to hear! Hope Raygun proves useful for you.
