### ISSUE TITLE
Incorrectly parsed stack frame for evaled code (?) in Chrome

### ISSUE THREAD

**Issue by ArturDorochowicz** [MindscapeHQ/raygun4js#182]
Raygun produces incorrect payload for particular exceptions.
This is with Raygun 2.3.0.

For the following exception (`console.log(e.stack)`) in Chrome 49:

```
"TypeError: Cannot read property 'a' of null
    at p.isChecklistSelected (http://localhost:56108/v/scripts/app.f28bfb03.js:25:14850)
    at fn (eval at <anonymous> (http://localhost:56108/v/scripts/vendor.513e41be.js:20:5490), <anonymous>:4:355)
    at n.$digest (http://localhost:56108/v/scripts/vendor.513e41be.js:18:20783)
    at n.$apply (http://localhost:56108/v/scripts/vendor.513e41be.js:18:22437)
    at f (http://localhost:56108/v/scripts/vendor.513e41be.js:17:29285)
    at q (http://localhost:56108/v/scripts/vendor.513e41be.js:17:31133)
    at XMLHttpRequest.v.onload (http://localhost:56108/v/scripts/vendor.513e41be.js:17:31676)"
```

I get the following payload

``` json
{
 "OccurredOn": "2016-04-13T07:28:50.839Z",
 "Details": {
  "Error": {
   "ClassName": "TypeError",
   "Message": "Cannot read property 'a' of null",
   "StackTrace": [
    {
     "LineNumber": 25,
     "ColumnNumber": 14850,
     "ClassName": "line 25, column 14850",
     "FileName": "http://localhost:56108/v/scripts/app.f28bfb03.js",
     "MethodName": "p.isChecklistSelected"
    },
    {
     "LineNumber": 4,
     "ColumnNumber": 355,
     "ClassName": "line 4, column 355",
     "FileName": "http://localhost:56108/v/scripts/vendor.513e41be.js:20:5490), <anonymous>",
     "MethodName": "fn (eval at <anonymous>"
    },
    {
     "LineNumber": 18,
     "ColumnNumber": 20783,
     "ClassName": "line 18, column 20783",
     "FileName": "http://localhost:56108/v/scripts/vendor.513e41be.js",
     "MethodName": "n.$digest"
    },
    {
     "LineNumber": 18,
     "ColumnNumber": 22437,
     "ClassName": "line 18, column 22437",
     "FileName": "http://localhost:56108/v/scripts/vendor.513e41be.js",
     "MethodName": "n.$apply"
    },
    {
     "LineNumber": 17,
     "ColumnNumber": 29285,
     "ClassName": "line 17, column 29285",
     "FileName": "http://localhost:56108/v/scripts/vendor.513e41be.js",
     "MethodName": "f"
    },
    {
     "LineNumber": 17,
     "ColumnNumber": 31133,
     "ClassName": "line 17, column 31133",
     "FileName": "http://localhost:56108/v/scripts/vendor.513e41be.js",
     "MethodName": "q"
    },
    {
     "LineNumber": 17,
     "ColumnNumber": 31676,
     "ClassName": "line 17, column 31676",
     "FileName": "http://localhost:56108/v/scripts/vendor.513e41be.js",
     "MethodName": "XMLHttpRequest.v.onload"
    }
   ]
  },
  "Environment": {
   "UtcOffset": 2,
   "Browser-Width": 1920,
   "Browser-Height": 959,
   "Screen-Width": 1920,
   "Screen-Height": 1080,
   "Color-Depth": 24,
   "Browser": "Mozilla",
   "Browser-Name": "Netscape",
   "Browser-Version": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36",
   "Platform": "Win32"
  },
  "Client": {
   "Name": "raygun-js",
   "Version": "2.3.0"
  },
  "UserCustomData": {},
  "Tags": [
   "client",
   "javascript",
   "angularjs"
  ],
  "Request": {
   "Url": "http://localhost:56108/v/#/project/reports/checklists",
   "QueryString": {},
   "Headers": {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36",
    "Referer": "",
    "Host": "localhost"
   }
  },
  "Version": "1.0.0.0"
 }
}
```

Please note the second stack frame that specifies the `FileName` as `http://localhost:56108/v/scripts/vendor.513e41be.js:20:5490), <anonymous>`. This value is obviously parsed incorrectly.

It is also later used as is by Raygun servers (due to source mapping of some sort I suppose) and we are seeing requests to that exact address. In our case, and we use IIS on Windows, they generate exceptions since the URL path is invalid.

The particular class of exceptions with problematic stack trace is from an Angular 1 application, minified with UglifyJS. Exception originates from a method on an Angular controller that is used in a view. AFAIS the stack frame that is parsed incorrectly is from evaled code (due to an angular template?).

I have not checked other browsers nor other Chrome versions nor non-minified application yet.

**Comment by fundead** [comment]
Thanks for the detailed report, looks like it will be enough for us to repro this behaviour in the Tracekit dependency which is doing the malformed parsing of that FileName. I have made a note to look at this in our next sprint for you.

Regards,

Callum Gavin
Raygun Limited

**Comment by fundead** [comment]
We've updated the regexes for the stacktrace parsing the in the latest v2.5.0 release, so the above stacktrace should now be sent correctly. If a similar issue is noted in future please open a new ticket and we'll take another look.
